language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y texinfo
env:
  - ENABLE_UCS4=
  - ENABLE_UCS4=--enable-ucs4
script: "./autogen.sh && ./configure $ENABLE_UCS4 && make && make check"
notifications:
  irc: "irc.oftc.net#liblouis"
